"""initial schema

Revision ID: 29d480c4c858
Revises: 
Create Date: 2026-08-29 15:19:27.803168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d480c4c858'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_registry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'REVOKED', name='agentstatus'), nullable=False),
    sa.Column('public_key', sa.String(), nullable=False),
    sa.Column('max_transaction_limit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_daily_limit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_requests_agent_id'), 'agent_requests', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_requests_created_at'), 'agent_requests', ['created_at'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('checkout_id', sa.String(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_agent_id'), 'audit_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_audit_events_checkout_id'), 'audit_events', ['checkout_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FLAT', name='discounttype'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_cart_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_code'), 'offers', ['code'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('agent_credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_credentials_agent_id'), 'agent_credentials', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_credentials_api_key_hash'), 'agent_credentials', ['api_key_hash'], unique=True)
    op.create_table('cart_mandates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('signature', sa.String(), nullable=False),
    sa.Column('signed_payload', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CONSUMED', 'EXPIRED', 'REVOKED', name='mandatestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_mandates_agent_id'), 'cart_mandates', ['agent_id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_product_id'), 'inventory', ['product_id'], unique=True)
    op.create_table('checkout_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'UPDATED', 'COMPLETED', 'FAILED', name='checkoutstatus'), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('offer_code', sa.String(), nullable=True),
    sa.Column('mandate_id', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('final_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_registry.id'], ),
    sa.ForeignKeyConstraint(['mandate_id'], ['cart_mandates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkout_sessions_agent_id'), 'checkout_sessions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_idempotency_key'), 'checkout_sessions', ['idempotency_key'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('checkout_session_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='orderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_registry.id'], ),
    sa.ForeignKeyConstraint(['checkout_session_id'], ['checkout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkout_session_id')
    )
    op.create_index(op.f('ix_orders_agent_id'), 'orders', ['agent_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(), nullable=True),
    sa.Column('razorpay_signature', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'AUTHORIZED', 'CAPTURED', 'FAILED', 'REFUNDED', name='transactionstatus'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('raw_webhook_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_order_id'), 'transactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_transactions_razorpay_order_id'), 'transactions', ['razorpay_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_razorpay_order_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_order_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_orders_agent_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_checkout_sessions_idempotency_key'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_agent_id'), table_name='checkout_sessions')
    op.drop_table('checkout_sessions')
    op.drop_index(op.f('ix_inventory_product_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_cart_mandates_agent_id'), table_name='cart_mandates')
    op.drop_table('cart_mandates')
    op.drop_index(op.f('ix_agent_credentials_api_key_hash'), table_name='agent_credentials')
    op.drop_index(op.f('ix_agent_credentials_agent_id'), table_name='agent_credentials')
    op.drop_table('agent_credentials')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_offers_code'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_checkout_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_agent_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_agent_requests_created_at'), table_name='agent_requests')
    op.drop_index(op.f('ix_agent_requests_agent_id'), table_name='agent_requests')
    op.drop_table('agent_requests')
    op.drop_table('agent_registry')
    # ### end Alembic commands ###
