"""add unique constraints on razorpay order and payment ids

Revision ID: 5680c898485b
Revises: 29d480c4c858
Create Date: 2026-08-30 19:40:29.467407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5680c898485b'
down_revision: Union[str, Sequence[str], None] = '29d480c4c858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_checkout_sessions_razorpay_order_id'), 'checkout_sessions', ['razorpay_order_id'], unique=True)
    # batch_alter_table (not a bare op.create_unique_constraint) is required
    # here: SQLite has no native ALTER TABLE ADD CONSTRAINT, only Alembic's
    # batch mode (copy-table-and-swap) can add a unique constraint to an
    # existing SQLite table. On Postgres, batch mode detects native ALTER
    # support and just emits a direct ALTER TABLE - no behavior change there.
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.create_unique_constraint('uq_transactions_razorpay_payment_id', ['razorpay_payment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.drop_constraint('uq_transactions_razorpay_payment_id', type_='unique')
    op.drop_index(op.f('ix_checkout_sessions_razorpay_order_id'), table_name='checkout_sessions')
    # ### end Alembic commands ###
